### ISSUE TITLE
Conflicts page

### ISSUE THREAD

**Issue by Arnostek** [Arnostek/TournamentSchedulerDjango#13]
schedule with marked conflicts - referee after playing, two matches one time ....

**Comment by VolkerGoeschl** [comment]
Should we differentiate conflicts?
eg: less than 3 or 2 matches break between playing / less than one between play and ref

**Comment by Arnostek** [comment]
less than 3 matches break is not conflict, it's just more fun :) I have stub of code in my other computer so I'll deal with this issue.

**Comment by Arnostek** [comment]
console sollution, may be it's enough
https://github.com/Arnostek/TournamentSchedulerDjango/blob/master/django/tournament/hotfixes/find_conflicts.py

**Comment by Arnostek** [comment]
It still needs some development, it probably doesn't check tph.

**Comment by Arnostek** [comment]
Fixed
