### ISSUE TITLE
Schedule move page

### ISSUE THREAD

**Issue by Arnostek** [Arnostek/TournamentSchedulerDjango#14]
Add posibility to switch matches  in schedule from web interface

**Comment by VolkerGoeschl** [comment]
switching is supposed to be with:
1) the previous/next game in the schedule 
2)  the p/n game on the same pitch
3) the p/n game in the division
(1. Is easy to do with javascript, for 2/3 I would do the switch serverside only and force a reload of the schedule)

**Comment by Arnostek** [comment]
I will do it easy way - admin page when you can move match to another schedule slot defined by match number.  I needed it to put all the finals on pitch 1 and made it from django shell.  Stub of code, which I used, already exists in https://github.com/Arnostek/TournamentSchedulerDjango/blob/master/django/tournament/hotfixes/switch_matches.py

**Comment by Arnostek** [comment]
I chaged the redirect link to live version: https://github.com/Arnostek/TournamentSchedulerDjango/commit/8faec09adfcd2c4760cf55646c3ad1d58b09b25d
