### ISSUE TITLE
Static pages don't work with Debug = False

### ISSUE THREAD

**Issue by Arnostek** [Arnostek/TournamentSchedulerDjango#19]

**Comment by VolkerGoeschl** [comment]
You need to set STATIC_ROOT and collect them
see: https://docs.djangoproject.com/en/2.2/howto/static-files/#deployment
on production servers static files are not supposed to be touched by django
my normal deployment is nginx as frontend (port 80) serving statics directly and forwarding everything else to django running inside apache via mod_wsgi (port(80xx)

**Comment by Arnostek** [comment]
I know, I need to add webserver into docker image. I have this already solved in my another project, I used uwsgi as webserver.

**Comment by Arnostek** [comment]
fixed in a156a711bc32e2e4b163746e2d67ecd70757d74f
