### ISSUE TITLE
Make schedule when there is less pitches than divisions

### ISSUE THREAD

**Issue by Arnostek** [Arnostek/TournamentSchedulerDjango#21]

**Comment by VolkerGoeschl** [comment]
Would you mind translating the comments in the TournamentScheduler / polygon_generator.
I might be of more help if I understand the code a bit better!

**Comment by Arnostek** [comment]
I translated comments in 84d74baa89589ee66c0f6656dee7cfa734263aa9, but polygon_generator.py is about issue https://github.com/Arnostek/TournamentSchedulerDjango/issues/9. Code for generating schedule is in TournamentScheduler.py and I would rather tune it by myself.

**Comment by Arnostek** [comment]
I'll also translate TournamentScheduler - but later

**Comment by Arnostek** [comment]
Solved by today's commits.
